/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.androiddevchallenge

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json

object DogsApi {
    private val json = Json { ignoreUnknownKeys = true }
    private val dogList: List<Animal> by lazy {
        json.decodeFromString(dogs)
    }

    fun fetchDogs(): List<Animal> = dogList

    fun fetchDog(id: Long): Animal = dogList.first {
        it.id == id
    }
}

@Serializable
data class Animal(
    @SerialName("ID")
    val id: Long,
    @SerialName("AnimalName")
    val name: String,
    @SerialName("PrimaryBreed")
    val species: String,
    @SerialName("Location")
    val location: String,
    @SerialName("Age")
    val age: Int,
    @SerialName("Sex")
    val sex: Sex,
    @SerialName("Photo1")
    val photo: String,
    @SerialName("Photo2")
    val photo2: String,
    @SerialName("Photo3")
    val photo3: String
)

enum class Sex {
    Male, Female
}

val dogs = """
    [{
    		"CompanyID": "1686",
    		"ID": "19570690",
    		"AnimalName": "Tiabini",
    		"Species": "Dog",
    		"Sex": "Female",
    		"Altered": "Yes",
    		"PrimaryBreed": "Retriever, Labrador",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Tan",
    		"SecondaryColor": "White",
    		"Age": "98",
    		"Size": "M",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "180.00",
    		"LastIntakeDate": "2021-02-15 10:47:00",
    		"Location": "K9 Back Hall",
    		"Dsc": "Tiabini is a beautiful, sweet and friendly girl looking for the right family to help her be her best self. She needs a family with dog experience and enough patience and understanding to set Tiabini up for success. She is a sweet and beautiful doggo, and she needs a forever home to share some of the love she has to give. Even at 8 years old, Tiabini will still melt your heart with her big brown puppy dog eyes. She is a sweet and gentle girl who warms up quickly to her humans. Her favourite things are making new human friends, treats, and her daily walks. She lives for her daily walks. They are literally her favourite thing in the world, besides you of course. She is a super smart girl who knows sit and touch, and she is definitely ready to learn more. Tiabini is easily excited, especially on her walks. This is a sign that she's really comfortable around you, but currently she sometimes barks or tries to chase dogs she wants to play with. She's working on this each day, and is happy to walk away with a gentle reminder from her walker. With encouragement, patience, and dedicated training, she will make even bigger strides of progressTiabini is a little nervous around new people, but all it takes is a little time and love while she gets to know you, and before you know it, she warms right up. Once she begins to trust you she will be a fiercely loyal companion to you forever. But it is important to note that Tiabini is not your typical cuddle bum - she is sensitive and will need her humans to appreciate that. Tiabini needs someone patient who can give her some space while she familiarizes herself with her new home. She does not do well with sudden and unexpected movements, which is why her new home should not have young children. She will do best in a low activity home and an overall quiet space while she gains her confidence and can feel comfortable in her new forever home. A home with a fenced in backyard is also recommended so that Tiabini can do some training outside. With patience and training, she can learn to adjust really well in her new home. She would do well in a house with low activity and people who can respect her need for space until she can find her confidence and feel comfortable with her family.Tiabini is looking for humans with previous dog experience (who understand dog body language) and who are willing to be calm, patient, and supportive of her as she navigates the world. She would do well in a house, not an apartment or a condo, in a quiet-ish neighbourhood where she can go on walks without getting too excited. It would be best if everyone in the home was at least 13+ and all were willing to take part in Tiabini's progress. Above all, Tiabini's humans need to be calm and gentle around her. She is a sweet girl and needs special care in her environment. Tiabini needs someone dedicated to training, building her confidence and trust, and showing her some love while she settles in. She is a sweet and beautiful doggo, and she needs a forever home to share some of the love she has to give. Ready to meet Tiabini and get the adoption process started? Start here: adopt-a-pet\/adoption-process<\/a>For more information on Tiabini, please contact us at adoption@torontohumanesociety.com<\/a>",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/c8e67597-427d-4e40-8fb3-1810b3be5611.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/fcf16676-ba56-419a-8642-883b13544a36.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/e9a96a7d-ee6e-48d6-8c35-feb55aa3baa7.jpg",
    		"OnHold": "No",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"DateOfSurrender": "2020-12-02 15:41:19",
    		"TimeInFormerHome": "0 ",
    		"ReasonForSurrender": "Aggression",
    		"PrevEnvironment": "Unknown ",
    		"LivedWithChildren": "Unknown",
    		"LivedWithAnimals": "Unknown",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "35 kilograms",
    		"DateOfBirth": "2013-01-03",
    		"ARN": "",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "Dog",
    		"AgeGroup": "Senior",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "1",
    		"ChipNumber": "982000197580068",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "39080046",
    		"AnimalName": "Ready",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Bulldog, American",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Brindle",
    		"SecondaryColor": "White",
    		"Age": "127",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2020-11-22 13:11:00",
    		"Location": "Fosters",
    		"Dsc": "Ready is a super sweet old timer with a big heart who loves being around his people. He is a quiet boy who rarely puts up a fuss. He is a down-to-earth kind of guy who is up for anything, whether that means cuddling on the couch or happily riding shotgun during your weekly errands, as long as it means spending time with you.Despite being an older guy, Ready is a real goofball who LOVES to play! Whether it is being chased around the living room, playing catch outside or a good old game of tug, Ready is down for it all. This easily excitable and silly guy loves being the centre of attention and will do just about anything for a good belly rub or a tasty treat. He is someone that knows what he wants and is not afraid to show you what toy he does or does not want to play with or simply get up and leave when he needs some alone time. Ready can also be a real diva at times, proudly strutting his stuff around the house with his feeding bowl in his mouth.Whoever said \"you can't teach an old dog new tricks\" has definitely never met a dog like Ready.He is incredibly smart and is eager to please his people.In order to challenge that smart mind of his and keep him engaged, Ready requires a significant amount of mental stimulation through activities such as people watching, puzzle feeders and his personal favourite: car rides.He is highly food motivated and catches onto new commands very quickly.In fact, it is safe to say that Ready does not eat to live but instead lives to eat!This handsome pup is someone who loves wholeheartedly and falls hard.For this reason, Ready tends to be a little protective of his people.He sometimes reacts in a less than favourable way towards certain dogs and strangers out on his walks.His prospective adopter must be willing to continue working with him on this through positive reinforcement and keeping encounters at a workable distance as he improves.Ready 's ideal home would be one with minimal stairs and away from populated areas, preferably with a fenced backyard with no other pets. It is also important to note that Ready has a high prey drive for small animals (i.e. squirrels, skunks, raccoons, etc). Additionally, Ready will require a family who will encourage him to stay active to keep his mobility up.This strong guy is wise beyond his years. His gaze has a softness and his eyes a depth unlike that of most pups. He has so much knowledge to share, and I promise he will do it all with the biggest of hearts while providing loads of slobbery kisses. As a sensitive and pure soul, Ready is prepared to give all of himself to his new owner(s) as their new best friend if given a chance.Ready dreams of treats, squirrels, belly scratches, and sloppy kisses, but most of all, he dreams of the day he gets to meet you.",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/b7821dc4-ceb3-4142-8ca0-d02cc914da4a.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/65bc7c60-8bcd-436b-b5a3-bd490d8baba2.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/17721197-eda6-46b8-8e79-b68109c9285a.jpg",
    		"OnHold": "No",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"DateOfSurrender": "2020-11-22 13:12:31",
    		"TimeInFormerHome": "0 ",
    		"ReasonForSurrender": "Health of Owner \/ Family",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "30 kilograms",
    		"DateOfBirth": "2010-07-10",
    		"ARN": "Rettie",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "Dog",
    		"AgeGroup": "Senior",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982000365458374",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	}, {
    		"CompanyID": "1686",
    		"ID": "42193849",
    		"AnimalName": "Gumaro",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Mixed Breed, Large",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Red",
    		"SecondaryColor": "",
    		"Age": "29",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2019-07-14 11:54:00",
    		"Location": "Fosters",
    		"Dsc": "Gumaro comes with 4 free training sessions! Gumaro is a silly bean of a pup with enough pep for everyone in the crew and then some. He's a grip it and rip it type who's very into chasing waves, crankin tunes, and racing you to that post over there. This here's a wild care of a guy looking for a fun pack of dudes and\/or dudettes to wild out with some treats and then (secretly) snuggle at the end of the day. Back in Mexico, Gumaro developed a reputation for being the silliest sweetie on the block. He's brought that crazy energy level with him to this cold place they call Canada. He's an excitable young dog who, like most homeless pups, hasn't been given the structure he needs to learn manners and foundation skills. But trust us when we say: this boy is willing to learn! Gumaro loves to run and run until he can't run anymore. Unfortunately, upon his arrival to Canada he had injured one of his hind legs, while this was healing, he fractured his other hind leg and had to have surgery for this one to heal. Can you imagine how frustrating this would be for an ants-in-your-pants boy like Gumaro? This guy's got one speed: fast! He needs to be running around in a dog park at the speed of treat. He has since completely recovered from these injuries but the restricted exercise was really tough for him as he didn't have an outlet for his high levels of energy. He couldn't run and play with other people and dogs and that has resulted in some leash reactivity. Gumaro loves other dogs and he also loves people. He would love to happily say hello to every person he sees. Thing is, you can't always get what you want. Especially when you're on a leash! When he can't say hello to people or other dogs, he can become quite frustrated. Frustrated to the point of barking and even lunging towards whoever he wants to see. This is something we are working on with him and is something he'll need to continue working on in his new home. Unfortunately, due to the location of our shelter and with Gumaro being in and out of foster homes we have not seen much success in his behaviour change. There is too much going on for him and he becomes over stimulated very quickly. He is a very keen boy and will, in the right environment and with the right people, learn super fast. Gumaro came to us as a puppy in July 2019, he hasn't had it easy in his short life but he is determined to find his forever home. The ideal home for Gumaro would be a family with a very active lifestyle. He would love to have a house with a fenced yard so that he can run around and play once his leg is all healed up. He would so best in a home outside of city limits or in a very quiet neighbourhood where his reactivity and exposure to triggers can be properly managed. His ideal humans have experience with high energy breeds while understanding (and being prepared to address) his tendency to jump up and shout when he doesn't get to run around freely. He is in need of some training and people who will be committed to work through his crazy puppy energy in a positive way. He could go home with older children so long as they are calm and considerate of his energetic personality. He could also go home with another dog, but he would need to meet him or her here at the shelter before he makes any decisions! Ideally the other dog should be around his size, small breed dogs may not be the best match for his rough and rowdy play style. This boy is full of life and love. He's got such a fun personality. He'll never say no to an adventure and will never leave your side once he gets to know you. He is just looking for what he's never been given: structure, routine, and a loving family to help guide him.What are you waiting for? Start the adoption process here: adopt-a-pet\/adoption-process<\/a>",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/d4bbcdd4-38b9-42ba-b2e8-e6b82b7f881a.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/f809d9e6-ecaf-4de8-94cf-dd48769c1774.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/a7a26406-9b7c-4dae-9daf-0b2b365d8928.jpg",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Completed",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "23 kilograms",
    		"DateOfBirth": "2018-09-12",
    		"ARN": "Gumaro",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982126055425890",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "42599113",
    		"AnimalName": "Steve",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Shepherd",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Brown",
    		"SecondaryColor": "",
    		"Age": "32",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2019-09-01 11:27:00",
    		"Location": "Fosters",
    		"Dsc": "Steve comes with 4 free training sessions!We all know Steve. He's the come-on-over, hey-it's-the-weekend buddy next door who loves having a tight group of friends to hang on the couch with. He throws the best parties and is the go-to for game night. Steve is, well, Steve is Steve. A happy and playful guy who will do just about anything for head pats and endless belly scratches.This belly-rub-loving, frolicking funhouse of butt wiggles and kissy kisses is a verified ladies man. Look at those eyes. That coat. How could he not be? This boy knows he's a looker and ain't afraid to turn it up for the ladies when he needs to. He can be so full of beans and loves prancing along to show off. He loves snuggling into his people's laps and getting all the attention.There are some things Steve is particular about. He really doesn't like being startled or stared at, and can be a little wary around men. As friendly a fella as Steve is, he definitely appreciates having the time to get to know people. He likes going at his own pace. No sudden, head-on hellos in other words. Rather, he prefers slow, steady, softly-spoken introductions. Tell Stevey he's the goodest, most handsomest boy ever, and you'll have a new best friend in no time. **Steve's foster parent experience**Steve has made huge improvements in his confidence and behaviour over the past few months. This is thanks in large part to a selfless foster parent who took him in at the height of the pandemic. With her help, he has been putting himself out there more and more, meeting new people and becoming friendly with the neighbours. The neighbours themselves even noticed his improvement.He hasn't just been making human friends. He's made some dog friends too! He has met various dogs of various sizes, and now has a four-legged best friend he plays with regularly. Cats are still uh, well, they aren't his favourite. He'll probably never be a cat guy. But that's okay, not everyone is!Steve and his foster parent have formed a deep bond. She thought she was helping him when she took him in. Turns out, he's been helping her. He has been the ultimate quarantine buddy. They do everything together - morning walks, breakfast , and gardening when the weather permits. He loves spending time chasing balls, chewing on sticks and squirrel watching. He is a big baby who will roll on his back at every chance for a belly rub.",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/c503109c-473c-49f0-9f8a-211c0f7b64ef.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/2efc4e37-e678-46f5-aafa-9df51da0a9df.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/b00401b6-20ee-4ef6-b3c2-991eae1e1499.jpg",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"DateOfSurrender": "2019-09-01 11:28:47",
    		"TimeInFormerHome": "0 ",
    		"ReasonForSurrender": "Medical Health of Animal",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "36 kilograms",
    		"DateOfBirth": "2018-07-03",
    		"ARN": "",
    		"VideoID": "-6mxL_DPKXg",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982126055419810",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	}, {
    		"CompanyID": "1686",
    		"ID": "43428782",
    		"AnimalName": "Kota",
    		"Species": "Dog",
    		"Sex": "Female",
    		"Altered": "Yes",
    		"PrimaryBreed": "Siberian Husky",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "White",
    		"SecondaryColor": "",
    		"Age": "19",
    		"Size": "M",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2019-12-15 09:09:00",
    		"Location": "Fosters",
    		"Dsc": "Kota is the bright-eyed bushy-tailed bestie you need in your life. She has that sunny and warm energy that'll get you through the winter. She'll also drag your butt outside and dive headfirst into the snow. She expects you'll follow her lead. She is gentle and intelligent, energetic and adventurous. Best of both worlds, she'll be your couch companion and your trusted trail partner. Kota is smart, real smart. She has a \"4. great\" GPA and she is well versed in the art of sit and shake and naps. She loves her toys, her snacks, and meeting dogs at the park. She is a burst of fresh air, a kibble enthusiast and aspiring athlete. She loves being around her humans, especially after a long day of activity. She poops herself right out and will find a spot next to you for her long, much-needed nap. Kota also loves working with her Foster Parent on her rehab exercises. You see, Kota got off to a rough start as a puppy. At five-months old, she was hit by a car. Both her front and back legs were severely injured. Nerve damage here, a fracture there, plus a bent wrist joint that dragged on the floor. Poor girl.Luckily, she was brought to Toronto Humane Society. It has been a long road to recovery, and it isn't over yet. She is working with her Foster Parents every day on her rehab exercises. She also visits Toronto Humane Society's rehab specialist for treatment, too. She has made strides though thanks to her energy, intelligence, and her Foster's commitment to getting her back on her paws! She loves being active. She loves exploring and playing and enjoying life - she won't let her past injuries stop her. She just did her first set of stairs! Go Kota!That being said, her adopters must be willing (and able) to support Kota on her recovery journey with regular visits to the vet and ongoing management of her physical challenges. In fact, she wears an orthotic device on her front limb that was custom-made just for her!She has a lot of specialized therapy ahead of her and she will look to you for support in every sense of the word. She will continue to heal, but will likely have a short back right leg and possibly some residual nerve damage in the front. So first and foremost, Kota needs humans who are ready to take her recovery on. She also needs humans who enjoy having fun. Kota lives for fun. She will cure any seasonal slump you might be in by showing you how to properly enjoy winter. She LOVES the snow. She dives in, digs around, snacks on it, and buries her face in the snowbanks. Her energy level is increasing now that her injuries are improving. Kota also has some tummy issues. She has what is called IBD (inflammatory bowel disease) which is a long term condition managed with consistent medications. She hopes her humans will help with her tummy and stay on top of her treatment.Kota is everything you'd want in a dog - she loves making new friends and cheering people up. She is a handful, even with her injuries, and her stamina might leave you pooped. She is looking for some dedicated, outdoor loving humans who can keep up with her as she spreads her doggy wings. Other dogs in the home? Great! Children? Well, supervised introductions first, please.To learn more about Kota, contact us adoption@torontohumanesociety.com<\/a>If you want to be a part of Kota's journey, begin the adoption process here: adopt-a-pet\/adoption-process<\/a>",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/28cd230a-33a3-41a6-b884-f67b94a48b84.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/dea5aedf-883b-4043-a49f-98cad35de12c.jpg",
    		"Photo3": "",
    		"OnHold": "No",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "27 kilograms",
    		"DateOfBirth": "2019-07-15",
    		"ARN": "",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982126055350791",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46030720",
    		"AnimalName": "Mac",
    		"Species": "Dog",
    		"Sex": "Female",
    		"Altered": "Yes",
    		"PrimaryBreed": "Border Collie",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Black",
    		"SecondaryColor": "Brown",
    		"Age": "87",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2020-11-05 12:45:00",
    		"Location": "Fosters",
    		"Dsc": "With her million dollar smile and pleased-to-flippin-meet-ya pawshake, Mac knows how to make an entrance. Her big brown eyes are usually what does it for people. But if her warm, loving, trusting, and comforting look doesn't make you feel squishy inside, her winning cuddle-at-first-sight persona will. Mac is such a sweetie. A good listener and devoted friend. While not the puppy she used to be, this beautiful gal is ready to start fresh with something new. Mac is a dog who loves being a part of the action. She loves group hangouts inside the home and out, and loves the feeling of being by your side. She is friendly around other dogs and can appreciate the beauty of the nature trail as well as any human can. She is an older gal so she doesn't have the pep she used to. Mac really loves to just hang out and relax and cuddle with her humans.What Mac doesn't like is when she is NOT part of the action. She has serious FOMO (fear of missing out), and doesn't like to be left alone for long periods of time. She doesn't make a mess or anything, but she will call out to you until you get home and sit your butt back on the couch so she can snuggle you. What helps with Mac's \"separation issues\" are distractions. Kong toys, music playing the background, a special dog walker who'll take her out on walks while you're gone. The best distraction of all? Another dog! Mac would love having another dog in the home and this would certainly help with her anxiety. Mac is currently taking anti anxiety medication to help her relax when she is feeling a little left out or lonely. Her adopters should be prepared to help her take her medication when she needs it. Toronto Humane Society staff will gladly provide you with all the information and guidance you need here. Mac is looking for a home where she'll get the friendship and connection she needs. She is a very affectionate girl who thrives when she is part of the group. Because she is a senior, she is not as active as she once was, and any young children in the home should be mindful of her age. Cuddles on the couch, head scratches, and kong toys. That's Mac's world. What are you waiting for? Mac's ready to claim that spot in your family room. To begin the adoption process, visit us at adopt-a-pet\/adoption-process<\/a>.To learn a little more about Mac, contact us at adoption@torontohumanesociety.com<\/a>.",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/f602ab97-e7ac-471f-b9d9-84f2f392c38a.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/450107e1-6c85-4727-98bf-a1516fe805b4.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/a455060e-ae7f-4024-867b-1e21246ec5bb.jpg",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "31 kilograms",
    		"DateOfBirth": "2013-11-07",
    		"ARN": "",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Senior",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982126059839248",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46273799",
    		"AnimalName": "Polar Bear",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Shepherd",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "White",
    		"SecondaryColor": "",
    		"Age": "50",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2020-12-22 16:44:00",
    		"Location": "Fosters",
    		"Dsc": "Polar Bear is a sweet, sweet boy who likes two things: the great outdoors, and people to snuggle up with after walks. Outside, find a stick and you're in for a fun game of tug. Inside, he'll press his forehead between your knees and slowly sink onto his back for belly rubs. This boy might be a polar bear, but he is also an energizer bunny. He keeps going and going. His fosters family have found that 2-3 hours is the sweet spot for walks. Any less than 2 hours per day and he gets antsy. Right now he doesn't have access to a backyard. Having one would be great because then he would get to hang out there and burn off all his energy.He has adapted very well to apartment living in general - he knows the elevator means treats and praise, he's rarely spooked by traffic, and he rides the subway like a pro. He also listens very well and loves to sit for treats! Though sometimes he can get distracted by all the new smells and sounds in the city. It sometimes takes a minute to get his attention at busy intersections, but he's getting much better. He's good at loose-leash walking as long as it's a familiar route without too many new smells to investigate. He's never yanked at the leash, but he will sneakily speed up little by little until he's tricked you into a power-walk. Be warned, he LOVES to sniff - especially when that sniff turns into munching whatever he's found on the sidewalk. He's quick and his foster parents have to watch carefully because it's hard to tell if he just wants to sniff another dog's scent, or if he's trying to get at a half-buried hamburger... or a piece of toast... or a styrofoam peanut... Out on walks, Polar Bear can be a little tense around big, fluffy dogs, but he's improving quickly. He's gotten a lot better at walking past big dogs without reacting. When he met another big dog off-leash in a backyard, he was playful and friendly, even if he didn't LOVE sharing the treats and toys. Unfortunately, he's a little too interested in his feline foster-sibling. Everyone would probably be more relaxed if there were no cats at his new home. Some things Polar Bear does NOT like: being confined and not knowing where you are. He's made a lot of great progress at his foster home - he went from hating his crate to being fine in it as long as his people are in the room - but he will whine (and even howl a little!) if he can't see or hear you. He needs someone patient to help him understand that his people will always, always come back for him. Never barks though! That doesn't mean he's not up for adventure, though! He walks, runs, and bounces with the best of 'em, and you'll be the one trying to keep up. Are you looking for a calm, snuggly boy the perfect size and temperament for hugs? Someone to help you appreciate your neighbourhood during long walks? Do you want a smart companion who will sit when you ask him to and be polite to strangers? A fluffy gentleman to curl beside you on the couch? You may have found your best friend. Begin the adoption process here adopt-a-pet\/adoption-process<\/a>",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/c5833bfb-bceb-4082-9b6b-e1d0702e6572.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/4f610259-4e96-4a90-b3b1-03f2a88d1514.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/d9ae8fac-2a59-4f9f-92b5-fad306c8cae9.jpg",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "30 kilograms",
    		"DateOfBirth": "2016-12-15",
    		"ARN": "",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "956000009467326",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46601618",
    		"AnimalName": "Franklin",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Shepherd",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Black",
    		"SecondaryColor": "Tan",
    		"Age": "48",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2021-02-07 07:54:00",
    		"Location": "Fosters",
    		"Dsc": "",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/85813c20-678d-4fc8-99d3-2abb923be071.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/2bd12ae4-52d3-4f29-8090-993d9e1f7ca7.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/397454a6-4e5a-4b5e-bbfe-7af2fb47196b.jpg",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Completed",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "35 kilograms",
    		"DateOfBirth": "2017-02-10",
    		"ARN": "Myrna",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982126059839226",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46631504",
    		"AnimalName": "John",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Retriever, Labrador",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Tan",
    		"SecondaryColor": "",
    		"Age": "24",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2021-02-18 11:00:00",
    		"Location": "Fosters",
    		"Dsc": "",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/c50303cf-fbd3-4553-a14e-848be8561340.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/27de6171-8c7c-43ce-ba9d-cdbc0343fb96.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/7a1ddf06-7ad3-4250-af87-a6d894b2f304.jpg",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Completed",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "36 kilograms",
    		"DateOfBirth": "2019-02-18",
    		"ARN": "",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Foster Home",
    		"ChipNumber": "982126059840318",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46658725",
    		"AnimalName": "Elias",
    		"Species": "Dog",
    		"Sex": "Male",
    		"Altered": "Yes",
    		"PrimaryBreed": "Hound",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Brown",
    		"SecondaryColor": "White",
    		"Age": "36",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2021-02-18 12:32:00",
    		"Location": "Room C",
    		"Dsc": "I am currently eligible for adoption matchmaking but not quite ready to go to my forever home. Please ask about me during your adoption counselling session for more information.",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/cc573441-df1a-4067-9060-2570b0ff4282.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/195c85b7-a3d6-4bde-87d5-3680e189b91f.jpg",
    		"Photo3": "https:\/\/g.petango.com\/photos\/1686\/416b1e9a-0798-4cf6-846e-8aed01e994e5.jpg",
    		"OnHold": "No",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Completed",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "42 kilograms",
    		"DateOfBirth": "2018-02-17",
    		"ARN": "",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "Dog",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Room C",
    		"ChipNumber": "981020035233708",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46687235",
    		"AnimalName": "Legolas",
    		"Species": "Dog",
    		"Sex": "Female",
    		"Altered": "Yes",
    		"PrimaryBreed": "Shepherd",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Blond",
    		"SecondaryColor": "",
    		"Age": "12",
    		"Size": "M",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2021-02-23 16:46:00",
    		"Location": "Room D 1",
    		"Dsc": "I am currently eligible for adoption matchmaking but not quite ready to go to my forever home. Please ask about me during your adoption counselling session for more information.",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/4e19ac99-873b-45bb-b064-7de1759187c7.jpg",
    		"Photo2": "",
    		"Photo3": "",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Completed",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "19 kilograms",
    		"DateOfBirth": "2020-02-23",
    		"ARN": "A46671266",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Run 7",
    		"ChipNumber": "982126059843470",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	},
    	{
    		"CompanyID": "1686",
    		"ID": "46687240",
    		"AnimalName": "Gollum",
    		"Species": "Dog",
    		"Sex": "Female",
    		"Altered": "Yes",
    		"PrimaryBreed": "Hound",
    		"SecondaryBreed": "Mix",
    		"PrimaryColor": "Brown",
    		"SecondaryColor": "",
    		"Age": "48",
    		"Size": "L",
    		"Housetrained": "Unknown",
    		"Declawed": "No",
    		"Price": "0.00",
    		"LastIntakeDate": "2021-02-23 16:46:00",
    		"Location": "Room D 1",
    		"Dsc": "I am currently eligible for adoption matchmaking but not quite ready to go to my forever home. Please ask about me during your adoption counselling session for more information.",
    		"Photo1": "https:\/\/g.petango.com\/photos\/1686\/311ec70f-b9d3-41c6-8404-70d811b06335.jpg",
    		"Photo2": "https:\/\/g.petango.com\/photos\/1686\/7ed0a940-eea7-491e-bc25-26879262be8d.jpg",
    		"Photo3": "",
    		"OnHold": "Yes",
    		"SpecialNeeds": "",
    		"NoDogs": "",
    		"NoCats": "",
    		"NoKids": "",
    		"BehaviorResult": "Complete",
    		"MemoList": "",
    		"Site": "Toronto Humane Society",
    		"TimeInFormerHome": "",
    		"ReasonForSurrender": "",
    		"PrevEnvironment": "",
    		"LivedWithChildren": "No",
    		"LivedWithAnimals": "No",
    		"LivedWithAnimalTypes": "",
    		"BodyWeight": "24 kilograms",
    		"DateOfBirth": "2017-02-23",
    		"ARN": "A46672225",
    		"VideoID": "",
    		"BehaviorTestList": "",
    		"Stage": "Available",
    		"AnimalType": "1",
    		"AgeGroup": "Adult",
    		"WildlifeIntakeInjury": "",
    		"WildlifeIntakeCause": "",
    		"BuddyID": "0",
    		"Featured": "No",
    		"Sublocation": "Run 10",
    		"ChipNumber": "985112007505056",
    		"ColorPattern": "",
    		"AdoptionApplicationUrl": "",
    		"BannerURL": "https:\/\/ws.petango.com\/webservices\/adoptablesearch\/images\/24PW-Pet-Insurance-Programs-150x84-with-white-space.png"
    	}
    ]
""".trimIndent()
